version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: next-commerce-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: commerce_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - next-commerce-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: next-commerce-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "15432:80"
    depends_on:
      - postgres
    networks:
      - next-commerce-network

volumes:
  postgres_data:

networks:
  next-commerce-network:
    driver: bridge